# Generated by Django 3.0.7 on 2020-07-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_school_name', models.CharField(max_length=250)),
                ('sp_school_located', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50)),
                ('sp_village_ward', models.CharField(blank=True, max_length=250)),
                ('sp_school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.School')),
            ],
        ),
    ]
