# Generated by Django 3.0.7 on 2020-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_name',
            field=models.CharField(max_length=250, verbose_name='School Name'),
        ),
    ]
