# Generated by Django 3.0.7 on 2020-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0002_auto_20200708_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_name',
            field=models.CharField(max_length=250),
        ),
    ]
