# Generated by Django 3.0.7 on 2020-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0004_auto_20200708_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_located',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50, verbose_name='1.2    Is the school located in Rural or Urban Area'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_name',
            field=models.CharField(max_length=250, verbose_name='1.1    School Name (In Capital Letters)'),
        ),
    ]
