# Generated by Django 3.0.7 on 2020-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0005_auto_20200709_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_located',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50, verbose_name='Is the school located in Rural or Urban Area'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_name',
            field=models.CharField(max_length=250, verbose_name='School Name (In Capital Letters)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_village_ward',
            field=models.CharField(blank=True, max_length=250, verbose_name='Village Name'),
        ),
    ]
