# Generated by Django 3.0.8 on 2020-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0007_schoolprofile_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_village_ward',
            field=models.CharField(blank=True, max_length=250, verbose_name='(a) Village Name'),
        ),
    ]
