# Generated by Django 3.0.8 on 2020-07-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0008_auto_20200710_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_habitation_mohalla',
            field=models.CharField(blank=True, max_length=250, verbose_name='Habitation name(for rural area)/Ward Number(for urban area)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_village_ward',
            field=models.CharField(blank=True, max_length=250, verbose_name='Village Name(for rural area)/Ward Number(for urban area)'),
        ),
    ]
