# Generated by Django 3.0.8 on 2020-07-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0009_auto_20200711_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_assembly',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the Assembly Constituency'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_cd',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of Community Development(CD)Block/Mandal/Taluka'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_city_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the city(where applicable)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_crc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name of the Cluster Resource Centre(CRC)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_ed',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the Educational Block'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_gram_panchayat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the Gram Panchayat(for rurul area only)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_municipality',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the Municipality(where applicable)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_parliamentary',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name of the Parliamentary Constituency'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pincode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pin Code'),
        ),
    ]
