# Generated by Django 3.0.8 on 2020-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0011_auto_20200711_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_school_category',
            field=models.CharField(blank=True, choices=[('Primary only with grades 1 to 5', 'Primary only with grades 1 to 5'), (2, 'Primary only with grades 1 to 8'), (3, 'Higher Secondary with grades 1 to 12'), (4, 'Upper Primary only with grades 6 to 8'), (5, 'Higher Secondary with grades 6 to 12'), (6, 'Secondary/Sr.Sec. with grades 1 to 10'), (7, 'Secondary/Sr.Sec. with grades 6 to 10'), (8, 'Secondary/Sr.Sec. with grades 9 and 10'), (9, 'Higher Secondary with grades 9 to 12'), (10, 'Hr.Sec. /Jr.College only with grades 11 and 12')], max_length=50, verbose_name='School Category'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_pincode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Pin Code'),
        ),
    ]
