# Generated by Django 3.0.8 on 2020-07-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0012_auto_20200711_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_highest_class',
            field=models.CharField(blank=True, max_length=10, verbose_name='(b)Highest Class in the School '),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_lowest_class',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a)Lowest Class in the School '),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_school_type',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-educational', 'Co-educational')], max_length=15, verbose_name='Type of School'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='sp_school_category',
            field=models.CharField(blank=True, choices=[('Primary only with grades 1 to 5', 'Primary only with grades 1 to 5'), ('Primary only with grades 1 to 8', 'Primary only with grades 1 to 8'), ('Higher Secondary with grades 1 to 12', 'Higher Secondary with grades 1 to 12'), ('Upper Primary only with grades 6 to 8', 'Upper Primary only with grades 6 to 8'), ('Higher Secondary with grades 6 to 12', 'Higher Secondary with grades 6 to 12'), ('Secondary/Sr.Sec. with grades 1 to 10', 'Secondary/Sr.Sec. with grades 1 to 10'), ('Secondary/Sr.Sec. with grades 6 to 10', 'Secondary/Sr.Sec. with grades 6 to 10'), ('Secondary/Sr.Sec. with grades 9 and 10', 'Secondary/Sr.Sec. with grades 9 and 10'), ('Higher Secondary with grades 9 to 12', 'Higher Secondary with grades 9 to 12'), ('Hr.Sec. /Jr.College only with grades 11 and 12', 'Hr.Sec. /Jr.College only with grades 11 and 12')], max_length=50, verbose_name='School Category'),
        ),
    ]
