# Generated by Django 3.0.8 on 2020-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0013_auto_20200711_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_all_weather_road',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Whether school is approachable by all-weather road?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_anganwadi',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='If yes,'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_anganwadi_children',
            field=models.CharField(blank=True, max_length=20, verbose_name='(b)Total Children in Anganwadi Centre'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_anganwadi_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='(a)Code of the Anganwadi Centre'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_anganwadi_worker',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='(c)Is the Anaganwadi worker trained in early childhood education'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_cce_higher_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(d) Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_cce_pri',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(a) Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_cce_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(c) Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_cce_upper_pri',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(b) Upper Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_counseling',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Does the school provide educational and vocational guidance/counseling to students?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_distance_higher_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='(d) From Higher Secondary school/Junior College'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_distance_primary',
            field=models.CharField(blank=True, max_length=20, verbose_name='(a) From Primary school/section'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_distance_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='(c) From Secondary school/section'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_distance_upper_primary',
            field=models.CharField(blank=True, max_length=20, verbose_name='(b) From Upper Primary school/section'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_establishment_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year of establishment of School'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_high_sec_affi_board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('State Board', 'State Board'), ('ICSE', 'ICSE'), ('International Board', 'International Board'), ('Others', 'Others'), ('Both CBSE & State Board', 'Both CBSE & State Board')], max_length=28, verbose_name='(b) For Higher Secondary Sections'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_high_sec_affi_board_number',
            field=models.CharField(blank=True, max_length=28, verbose_name='Affiliation Number'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_higher_secondary_avg_chil_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(e) Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_higher_secondary_avg_teach_days',
            field=models.CharField(blank=True, max_length=8, verbose_name='(e) Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_higher_secondary_ins_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(e) Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_higher_secondary_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='(d)Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_is_cwsn',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Is this a special school for CWSN?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_is_residential',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Is this a residential school?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_is_shift',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Is this a shift school?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_majority',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Are majority of the pupils taught through their mother tongure at the primary level?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_management_code',
            field=models.CharField(blank=True, choices=[('Department of Education', 'Department of Education'), ('Tribal Welfare Department', 'Tribal Welfare Department'), ('Local Body', 'Local Body'), ('Government Aided', 'Government Aided'), ('Private Unaided(Recognized)', 'Private Unaided(Recognized)'), ('Other Govt. managed schools', 'Other Govt. managed schools'), ('Unrecognized', 'Unrecognized'), ('Social Welfare Department', 'Social Welfare Department'), ('Ministry of Labour', 'Ministry of Labour'), ('Kendriya Vidyalaya / Central School', 'Kendriya Vidyalaya / Central School'), ('Jawahar Navodaya Vidyalaya', 'Jawahar Navodaya Vidyalaya'), ('Sainik School', 'Sainik School'), ('RailwaySchool', 'RailwaySchool'), ('Central Tibetan School', 'Central Tibetan School'), ('Madarsa Recognized(by Wakf board/Madarsa Board)', 'Madarsa Recognized(by Wakf board/Madarsa Board)'), ('Madarsa Unrecoginzed', 'Madarsa Unrecoginzed')], max_length=50, verbose_name='Management of the school'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_minority',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Is this a minority managed school?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_minority_type',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Jain', 'Jain'), ('Christian', 'Christian'), ('Parsi', 'Parsi'), ('Buddhist', 'Buddhist'), ('Any other', 'Any other'), ('Linguistic Minority', 'Linguistic Minority')], max_length=30, verbose_name='(a)If yes, Type of minority community managing the school'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_others_high_sec_affi_board',
            field=models.CharField(blank=True, max_length=28, verbose_name=' If others,then name of the board'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_others_sec_affi_board',
            field=models.CharField(blank=True, max_length=28, verbose_name='If others,then name of the board'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pre_primary',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Whether pre-primary section(other than Anganwadi) attached to school?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pre_primary_avg_chil_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(a) Pre-primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pre_primary_avg_teach_days',
            field=models.CharField(blank=True, max_length=8, verbose_name='(a) Pre-primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pre_primary_ins_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(a) Pre-primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pre_vocational_course',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Does the school offer any pre-vocational course(s) at the Upper-Primary stage?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_pri_to_upper_pri_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='(a)Primary to Upper Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_primary_avg_chil_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(b) Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_primary_avg_teach_days',
            field=models.CharField(blank=True, max_length=8, verbose_name='(b) Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_primary_ins_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(b) Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_primary_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a)Primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_rec_maintained',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(a) Are cumulative records of pupil being maintained?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_rec_shared',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='(b) Are cumulative records of pupil being shared with parents?'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_residential_type',
            field=models.CharField(blank=True, choices=[('Ashram(Govt.)', 'Ashram(Govt.)'), ('Non-ashram(Govt.)', 'Non-ashram(Govt.)'), ('Private', 'Private'), ('Others', 'Others'), ('KGBV', 'KGBV'), ('Model School', 'Model School'), ('Eklavya Model', 'Eklavya Model')], max_length=50, verbose_name='(a)If Yes, Type of residential school'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_sec_affi_board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('State Board', 'State Board'), ('ICSE', 'ICSE'), ('International Board', 'International Board'), ('Others', 'Others'), ('Both CBSE & State Board', 'Both CBSE & State Board')], max_length=28, verbose_name='(a) For Secondary Sections'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_sec_affi_board_number',
            field=models.CharField(blank=True, max_length=28, verbose_name='Affiliation Number'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_sec_to_upper_sec_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='(c)Secondary to Higher Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_secondary_avg_chil_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(d) Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_secondary_avg_teach_days',
            field=models.CharField(blank=True, max_length=8, verbose_name='(d) Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_secondary_ins_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(d) Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_secondary_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='(c)Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_upper_pri_to_sec_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='(b)Upper Primary to Secondary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_upper_primary_avg_chil_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(c) Upper primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_upper_primary_avg_teach_days',
            field=models.CharField(blank=True, max_length=8, verbose_name='(c) Upper primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_upper_primary_ins_days',
            field=models.CharField(blank=True, max_length=5, verbose_name='(c) Upper primary'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sp_upper_primary_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='(b)Upper Primary'),
        ),
    ]
