# Generated by Django 3.0.8 on 2020-07-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0015_physicalfacilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalfacilities',
            old_name='sp_school',
            new_name='pf_school',
        ),
    ]
