# Generated by Django 3.0.8 on 2020-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0016_auto_20200711_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_boundary_type',
            field=models.CharField(blank=True, choices=[('Pucca', 'Pucca'), ('Pucca but broken', 'Pucca but broken'), ('Barbed wire fencing', 'Barbed wire fencing'), ('Hedges', 'Hedges'), ('boundary walls', 'boundary walls'), ('others', 'others'), ('Partial', 'Partial'), ('Under Construction', 'Under Construction')], max_length=50, verbose_name='Type of boundary wall'),
        ),
    ]
