# Generated by Django 3.0.8 on 2020-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0017_physicalfacilities_pf_boundary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_arts_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(d) Co-curricular activity room/arts and crafts room'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_available',
            field=models.CharField(blank=True, max_length=10, verbose_name='(b) Total number of rooms other than classrooms available in School:'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_construction',
            field=models.CharField(blank=True, max_length=50, verbose_name='(a2) No. of Classrooms under construction'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional',
            field=models.CharField(blank=True, max_length=50, verbose_name='(a1) No. of Classrooms used for instructional purposes'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional_higher_sec',
            field=models.CharField(blank=True, max_length=10, verbose_name='Higher Secondary'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional_pre_pri',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pre-primary'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional_pri',
            field=models.CharField(blank=True, max_length=10, verbose_name='Primary'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional_sec',
            field=models.CharField(blank=True, max_length=10, verbose_name='Secondary'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_classrooms_instructional_upper_pri',
            field=models.CharField(blank=True, max_length=10, verbose_name='Upper primary'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_comp_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(h) Computer room'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_de_worming_given',
            field=models.CharField(blank=True, choices=[('Complete(two doses)', 'Complete(two doses)'), ('Partially(one dose)', 'Partially(one dose)'), ('Not given', 'Not given')], max_length=20, verbose_name='(b)De-worming tablets given to children?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_dilapidated',
            field=models.CharField(blank=True, max_length=50, verbose_name='(a3) Total Classrooms in dilapidated condition'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_drinking_water_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether drinking water is available in the school premises?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_dustbins_class',
            field=models.CharField(blank=True, choices=[('Yes and all', 'Yes and all'), ('No', 'No'), ('Yes but some', 'Yes but some')], max_length=41, verbose_name='(a) Class room'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_dustbins_kitchen',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=41, verbose_name='(c) kitchen'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_dustbins_toilet',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=41, verbose_name='(b) Toilet'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_electricity_connection',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=30, verbose_name='Whether electricity connection is available in the school ?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_equip_audio',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=100, verbose_name='(a) Audio/Visual/Public Address System'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_equip_biometric',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=100, verbose_name='(d) Biometric device'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_equip_math_kit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=100, verbose_name='(c) Math kit'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_equip_sci_kit',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=100, verbose_name='(b) Science Kit'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_hand_rails',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='(a) If yes,whether Hand-rails for ramp is available?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_hand_soap_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(b) Is hand washing facility with soap available near toilets/urinals block?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_hand_washing_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether hand washing facility with soap available for available for washing hands before and after meal?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_for_teaching',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether ICT based tools are used for teaching?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_for_teaching_hours',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a) If yes, Number of Hours spent per week'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_functional',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='(b)Whether ICT lab is functional or not?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_instructor',
            field=models.CharField(blank=True, choices=[('Full time', 'Full time'), ('Part Time', 'Part Time'), ('Not Available', 'Not Available')], max_length=100, verbose_name='(d)Type of ICT instructor in the School?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_model',
            field=models.CharField(blank=True, choices=[('BOOT Model', 'BOOT Model'), ('BOO Model', 'BOO Model'), ('Other', 'Other')], max_length=100, verbose_name='(c)Which Model is implemented in the School?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ict_year',
            field=models.CharField(blank=True, max_length=100, verbose_name='(a)Year of implementation'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_incinerator_girls',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(c) Whether incinerator is available in/attached to girls toilet?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_iron_folic',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='(c)Iron and Folic acid tablets given to children'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_kitchen_garden',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Whether Kitchen Garden is available in school?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_land_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether land is available for expansion of school facilities'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_lib_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(g) Library room'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_librarian',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name=' Does the school have a full-time librarian?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_magazine',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name=' Does the School subsribe to newspapers/magazines?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_medical_check_up',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Whether Medical check-up is conducted(last year)?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_number_hand_washing',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a) Number of wash points'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_other_arrangement',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=28, verbose_name='(a) if no, whether school has made adequate arrangements for children to play outdoor games and other physical activities in an adjoining playground/municipal park etc.'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_playground_facility',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=28, verbose_name='Whether Playground facility is available?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_purifier_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=25, verbose_name='Whether water purifier/RO is available in the school?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_rain_harvesting',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Does the school have provision for rain water harvesting?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_ramp_disabled',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Whether ramp for disabled children to access school building exists?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_school_special_edu',
            field=models.CharField(blank=True, choices=[('Dedicated', 'Dedicated'), ('At cluster level', 'At cluster level'), ('No', 'No')], max_length=20, verbose_name='Whether School has special educator?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_schools_toilet',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Does the school have toilet?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_science_lab_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(f) Integrated Science laboratory(integrated laboratory is the one in which Physics,Chemistry and Biology practical are held)for Secondary sections only'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_sep_girls_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(b) Separate common room for girls'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_sep_room_head_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(a) Separate Room for Assistant Head Teacher/Vice principal'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_separate_head_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether separate room for Head Teacher/Principle available'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_solar_panel',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Yes, but not functional', 'Yes, but not functional')], max_length=30, verbose_name='Whether solar panel available in school?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_staff_quarters_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(e) Staff quarters(including residential quarters for Head Teacher/Principal and Asst. Head Teacher/Vice Principal)'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_staff_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(c) Staffroom for teachers'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_students_furniture',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='No. of Students for whom furniture is available?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_tinkering_sec',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='(i) Tinkering Lab'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_total_medical_check_ups',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a)Total Number of  Medical check-ups is conducted(last year)?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_water_available',
            field=models.CharField(blank=True, max_length=10, verbose_name='(a) How many have running water available in the toilet/urinal for flushing and cleaning?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_water_testing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Whether water quality is tested from water testing lab?'),
        ),
        migrations.AddField(
            model_name='physicalfacilities',
            name='pf_which_comp_lab',
            field=models.CharField(blank=True, choices=[('ICT', 'ICT'), ('CAL', 'CAL'), ('Both', 'Both'), ('None', 'None')], max_length=100, verbose_name='Which Computer lab is available in the School?'),
        ),
    ]
