# Generated by Django 3.0.7 on 2020-07-08 15:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_school_admin', models.BooleanField(default=False)),
                ('is_block_admin', models.BooleanField(default=False)),
                ('is_district_admin', models.BooleanField(default=False)),
                ('is_state_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=250)),
                ('school_board', models.CharField(choices=[('', 'Board'), ('NA', 'NA'), ('CBSE', 'CBSE'), ('State Board', 'State Board'), ('ICSE', 'ICSE')], default='CBSE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_board', models.CharField(blank=True, choices=[('', 'Board'), ('NA', 'NA'), ('CBSE', 'CBSE'), ('State Board', 'State Board'), ('ICSE', 'ICSE')], default='CBSE', max_length=100)),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('subject_class', models.CharField(blank=True, choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=50)),
                ('subject_type', models.CharField(blank=True, choices=[('Scholastic', 'Scholastic'), ('Co -Scholastic', 'Co -Scholastic')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_class', models.CharField(blank=True, choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=5)),
                ('stud_section', models.CharField(blank=True, choices=[('', 'Section'), ('NA', 'NA'), ('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E'), ('F', 'Section F')], default='NA', max_length=5)),
                ('stud_rollno', models.CharField(max_length=10)),
                ('stud_mother_name', models.CharField(blank=True, max_length=200)),
                ('stud_stream', models.CharField(blank=True, choices=[('', 'Stream'), ('NA', 'NA'), ('Commerce', 'Commerce'), ('Electrical Technology', 'Electrical Technology'), ('Humanities', 'Humanities'), ('Information Technology', 'Information Technology'), ('PCM', 'PCM'), ('PCB', 'PCB'), ('Tourism', 'Tourism')], default='NA', max_length=30)),
                ('stud_parents_no_primary', models.CharField(blank=True, max_length=15)),
                ('stud_parents_no_alternative', models.CharField(blank=True, max_length=15)),
                ('stud_admission_year', models.CharField(blank=True, max_length=20)),
                ('stud_disability', models.CharField(blank=True, max_length=250)),
                ('stud_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_designation', models.CharField(blank=True, max_length=80)),
                ('emp_appointment_status', models.CharField(blank=True, choices=[('', 'Appointment Status'), ('Regular', 'Regular'), ('Temporary', 'Temporary'), ('Contract', 'Contract')], max_length=30)),
                ('emp_joining_date', models.DateField(null=True)),
                ('emp_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
